
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { Metadata } from "next";
import { QueryClientProvider, queryClient } from "./queryClient";
 "./queryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <body className={inter.className}> <QueryClientProvider client={queryClient}>{children}</QueryClientProvider></body>
      </body>
    </html>
  );
}
