
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { Metadata } from "next";
import { QueryClientProvider, queryClient } from "./util/queryClient";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Learning Path',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const DynamicHeader = dynamic(() => import("./components/Header"));

  return (
    <html lang="en">
      <body className={inter.className}> 
       <QueryClientProvider client={queryClient}>
       <DynamicHeader />
        {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
