services:
- type: web
  name: next-js
  env: node
  plan: starter
  buildCommand: npm run build
  startCommand: npm run start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production
# Uncomment the following to deploy this app as a static site on render
# - type: web
#   name: nextjs-static
#   env: static
#   buildCommand: npm install && npm run build && npm run export
#   staticPublishPath: .next
#   pullRequestPreviewsEnabled: true     # optional
#   envVars:
#   - key: NODE_ENV
#     value: production
