# default connection pool
debug: true
spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@learningpathcluster.xszn5ys.mongodb.net/${DB_NAME}
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
token:
  signing:
    key: ${TOKEN_SIGNING_KEY}