# default connection pool
debug: true
spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/learningPath?authSource=admin
      database: learningPath


  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

token:
  signing:
    key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
