# default connection pool
debug: true
spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/
      database: learningPath
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
